apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: spoke-install
  namespace: spoke
spec:
  clusterDeploymentRef:
    name: spoke
  imageSetRef:
    name: spoke-4.16.15
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.30.0.0/16
    machineNetwork:
      - cidr: 192.168.130.0/24
  provisionRequirements:
    controlPlaneAgents: 1
  # Generate with: cat ~/.ssh/id_rsa.pub
  sshPublicKey: REPLACE_SSH_PUBLIC_KEY
