apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: spoke
  namespace: spoke
spec:
  baseDomain: baremetal.local
  clusterName: spoke
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: spoke-install
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster: spoke
  pullSecretRef:
    name: pull-secret
